### PR TITLE
graphs: remember settings.

### PR DESCRIPTION
**Pull request by artur79**

### CODE REVIEW

**Comment by artur79** [comment]
Remembers graph kind and graph time scope as well.

**Review by barbarawuk — COMMENTED** [review]
I'm getting a few issues when trying this out in the browser. 

If I select monthly, the x axis labels are by month but the data points are still weekly.

Screenshot 2021-03-23 at 08 21 24

Reset doesn't seem to reset the filters any more.

Switching between Percentage Delivered and Planned vs Actual  doesn't seem to work unless click on Filter?

**Comment by artur79** [comment]
> I'm getting a few issues when trying this out in the browser.
> 
> If I select monthly, the x axis labels are by month but the data points are still weekly.
> 
> Screenshot 2021-03-23 at 08 21 24
> 
> Reset doesn't seem to reset the filters any more.
> 
> Switching between Percentage Delivered and Planned vs Actual doesn't seem to work unless click on Filter?

Good spot, checking. Unfortunately we can not spec what is drawn inside canvas

**Comment by artur79** [comment]
@barbarawuk fixed

**Review by barbarawuk — APPROVED** [review]
Brilliant 🥇 
This makes it all so much more easier to use now as you move around the pages.

**Pull request merged**
